# Generated by Django 5.1.1 on 2024-09-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGAdminTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'pgadmin_table',
            },
        ),
    ]
